#include<bits/stdc++.h>
using namespace std;

struct Job{
    int id;
    int profit;
    int deadline;
};

// Find maxm profit that can be generated by job scheduling

bool cmp(Job a, Job b)
{
    return (a.profit > b.profit);
}

int maxmProfit(Job arr[], int n)
{
    sort(arr,arr+n, cmp);

    int maxmDeadline = INT_MIN;

    for(int i=0;i<n;i++)
    {
        maxmDeadline = max(maxmDeadline,arr[i].deadline);
    }

    vector<int> schedule(maxmDeadline+1, -1);

    int total = 0;

    for(int i=0;i<n;i++)
    {
        int currProfit = arr[i].profit;
        int currID = arr[i].id;
        int currDeadline = arr[i].deadline;

        for(int j=currDeadline ; j>0 ; j--)
        {
            if(schedule[j] == -1)
            {
                total += currProfit;
                schedule[j] = currID;
                break;
            }
        }
    }

    return total;

}

int main(){

    

    return 0;
}